### ISSUE TITLE
Fails to run.  SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by jagibson** [hiddentao/ansijet#14]
Fails to run on Ubuntu 14.04.02 LTS

$ nodejs -v
v0.11.15

$ NODE_ENV=production ./start-app.js
/usr/bin/env: node --harmony: No such file or directory

$ NODE_ENV=production nodejs ./start-app.js 
/home/vagrant/ansijet/start-app.js:14
co(function*() {
           ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by hiddentao** [comment]
It needs the `--harmony` command-line flag to work. I'm slowly working on a new version which will auto-fix this.

**Comment by navindharman** [comment]
resolved --harmony issue by changing start-app.js
From, 
**#!/usr/bin/env node --harmony**
To,
**#!/usr/bin/node --harmony**

and still facing issue in below error,
[root@release ansijet]# NODE_ENV=production  ./start-app.js

/opt/ansijet/start-app.js:14
co(function*() {
           ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by navindharman** [comment]
resolved --harmony issue by changing start-app.js
From,
#!/usr/bin/env node --harmony
To,
#!/usr/bin/node --harmony
Note: based on distribution , try using whereis command to identify node path

For SyntaxError: Unexpected token *
Install node version and npm in below version:
# node -v
v6.11.0
# npm -v
3.10.10
