### ISSUE TITLE
Added first trigger error

### ISSUE THREAD

**Issue by navindharman** [hiddentao/ansijet#19]
I have added first playbook and selected the playbook and create new trigger(both drone and simple) , I am receiving below mentioned error,
2017-06-17T07:05:59.452Z - error: TypeError: /opt/ansijet/src/views/_mixins.jade:139
    137|           .help #{field.helpText}
    138|
  > 139|         if fieldErrors[fieldName]
    140|           - each errorMeta, errorId in fieldErrors[fieldName].errors
    141|             div.error #{errorMeta.msg}
    142|

Cannot read property 'description' of undefined
    at Object.eval (eval at <anonymous> (/opt/ansijet/node_modules/waigo/node_modules/jade/lib/jade.js:172:8), <anonymous>:143:17)
    at Object.jade_mixins.form (eval at <anonymous> (/opt/ansijet/node_modules/waigo/node_modules/jade/lib/jade.js:172:8), <anonymous>:359:4)
    at eval (eval at <anonymous> (/opt/ansijet/node_modules/waigo/node_modules/jade/lib/jade.js:172:8), <anonymous>:1447:20)
    at eval (eval at <anonymous> (/opt/ansijet/node_modules/waigo/node_modules/jade/lib/jade.js:172:8), <anonymous>:1480:22)
    at Object.exports.renderFile (/opt/ansijet/node_modules/waigo/node_modules/jade/lib/jade.js:290:21)
    at exports.jade (/opt/ansijet/node_modules/waigo/node_modules/co-views/node_modules/co-render/node_modules/consolidate/lib/consolidate.js:164:10)
    at Object.<anonymous> (/opt/ansijet/node_modules/waigo/node_modules/co-views/node_modules/co-render/index.js:33:5)
    at next (/opt/ansijet/node_modules/waigo/node_modules/koa/node_modules/co/index.js:99:21)
    at Object.<anonymous> (/opt/ansijet/node_modules/waigo/node_modules/koa/node_modules/co/index.js:56:5)
    at Object.next (/opt/ansijet/node_modules/waigo/node_modules/koa/node_modules/co/index.js:99:21)

**Comment by hiddentao** [comment]
That's strange, it must be be an unexpected error that doesn't have the necessary fields set. Unfortunately, I haven't been using ansijet for a couple of years now so it might be a while before I can take a good look at this.
